<?php
namespace modava\slide\components;

use backend\components\MyController;

class MySlideController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
